export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const CURRENT = "CURRENT"
export const FAIL = "FAIL"
export const GET_PROFILES = "GET_PROFILES"
export const GET_ONE_PROFILE = "GET_ONE_PROFILE"